### ISSUE TITLE
Issue 1 

### ISSUE THREAD

**Issue by adl409** [adl409/SE-project-Group-5#1]
Create and finish documenting the SRS document

**Comment by adl409** [comment]
Finished Section 3 of the SRS document

**Comment by wchen2654** [comment]
Finished Section 2 and Cover Title of the SRS document

**Comment by Na7hanL** [comment]
Finished Sections 1 and 5 of the SRS document

**Comment by adl409** [comment]
Updated and finalized the SRS document in the main branch
